import { useEffect, useMemo, useState } from "react";
import { CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { getCustomerTrend, getRevenueUnitTrend } from "../api/businessInsightsApi";
import type { CustomerTrendResponse, RevenueUnitTrendResponse } from "../types/businessInsights";

interface Props { businessDate: string; }
type Period = "WEEK" | "MONTH" | "THREE_MONTHS";
type RevenueTotals = { hotel:number; foodBeverage:number; onsen:number; spa:number; other:number; total:number; };
const DAYS: Record<Period, number> = { WEEK: 7, MONTH: 30, THREE_MONTHS: 90 };
const UNIT_COLORS = ["#22c7ff", "#19bf73", "#f59e0b", "#8b5cf6", "#94a3b8"];
function shortDate(value: string) { const p=value.split("-"); return p.length===3?`${p[2]}/${p[1]}`:value; }
function money(value:number){return new Intl.NumberFormat("vi-VN",{maximumFractionDigits:0}).format(value);}
function startOfWeek(date:string){const d=new Date(`${date}T00:00:00`);const day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d.toISOString().slice(0,10);}
function aggregate<T extends Record<string,any>>(data:T[],period:Period,sumKeys:string[]){if(period==="WEEK")return data.map(row=>({...row,label:shortDate(String(row.date))}));const groups=new Map<string,Record<string,any>>();for(const row of data){const key=startOfWeek(String(row.date));const item=groups.get(key)??{date:key,label:`Tuần ${shortDate(key)}`};for(const field of sumKeys)item[field]=Number(item[field]??0)+Number(row[field]??0);groups.set(key,item);}return[...groups.values()];}
function Kpi({label,value,note}:{label:string;value:string;note?:string}){return <div style={{border:"1px solid rgba(148,163,184,.15)",borderRadius:7,padding:"9px 10px",background:"rgba(8,28,42,.42)"}}><div style={{fontSize:9,color:"#8ba1b6",fontWeight:600}}>{label}</div><div style={{marginTop:4}}><strong style={{fontSize:15,color:"#edf6fb"}}>{value}</strong></div>{note&&<div style={{fontSize:9,color:"#7890a2",marginTop:4}}>{note}</div>}</div>;}

export default function BusinessInsightsPanel({businessDate}:Props){
 const[period,setPeriod]=useState<Period>("WEEK");const[customers,setCustomers]=useState<CustomerTrendResponse|null>(null);const[revenue,setRevenue]=useState<RevenueUnitTrendResponse|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState(false);const days=DAYS[period];
 useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setError(false);const[c,r]=await Promise.allSettled([getCustomerTrend(businessDate,days),getRevenueUnitTrend(businessDate,days)]);if(cancelled)return;setCustomers(c.status==="fulfilled"?c.value:null);setRevenue(r.status==="fulfilled"?r.value:null);setError(c.status==="rejected"&&r.status==="rejected");setLoading(false);}load();return()=>{cancelled=true;};},[businessDate,days]);
 const customerData=useMemo(()=>aggregate(customers?.data??[],period,["adults","children","unknownAge"]),[customers,period]);
 const revenueData=useMemo(()=>aggregate(revenue?.data??[],period,["hotel","foodBeverage","onsen","spa","other"]).map(row=>({...row,total:Number(row.hotel??0)+Number(row.foodBeverage??0)+Number(row.onsen??0)+Number(row.spa??0)+Number(row.other??0)})),[revenue,period]);
 const customerTotals=useMemo(()=>customerData.reduce((a,x)=>({adults:a.adults+Number(x.adults??0),children:a.children+Number(x.children??0),unknown:a.unknown+Number(x.unknownAge??0)}),{adults:0,children:0,unknown:0}),[customerData]);
 const revenueTotals=useMemo(()=>revenueData.reduce<RevenueTotals>((a,x)=>({hotel:a.hotel+Number(x.hotel??0),foodBeverage:a.foodBeverage+Number(x.foodBeverage??0),onsen:a.onsen+Number(x.onsen??0),spa:a.spa+Number(x.spa??0),other:a.other+Number(x.other??0),total:a.total+Number(x.total??0)}),{hotel:0,foodBeverage:0,onsen:0,spa:0,other:0,total:0}),[revenueData]);
 const revenueMix=[{name:"Hotel",value:revenueTotals.hotel},{name:"F&B",value:revenueTotals.foodBeverage},{name:"Onsen",value:revenueTotals.onsen},{name:"Spa",value:revenueTotals.spa},{name:"Other",value:revenueTotals.other}];
 const latestCustomer=customerData.at(-1);const latestCustomerValue=Number(latestCustomer?.adults??0)+Number(latestCustomer?.children??0);
 const latestRevenue=revenueData.at(-1);const latestRevenueValue=Number(latestRevenue?.total??0);
 const latestLabel=period==="WEEK"?`Ngày ${shortDate(businessDate)}`:`Tuần hiện tại · đến ${shortDate(businessDate)}`;
 if(loading)return <div style={{minHeight:360,display:"grid",placeItems:"center",color:"#7f96a8",fontSize:13}}>Đang tải phân tích kinh doanh...</div>;
 if(error)return <div style={{minHeight:360,display:"grid",placeItems:"center",color:"#f87171",fontSize:13}}>Không tải được dữ liệu phân tích kinh doanh.</div>;
 return <div style={{display:"grid",gap:14,width:"100%",fontSize:11}}>
  <div style={{display:"flex",justifyContent:"flex-end"}}><select value={period} onChange={e=>setPeriod(e.target.value as Period)} style={{background:"#071827",color:"#d8e3ea",border:"1px solid #18506c",borderRadius:6,padding:"6px 26px 6px 10px",fontSize:11}}><option value="WEEK">1 tuần</option><option value="MONTH">1 tháng</option><option value="THREE_MONTHS">3 tháng</option></select></div>
  {customers&&<section style={{borderBottom:"1px solid rgba(148,163,184,.12)",paddingBottom:12}}>
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginBottom:8}}><div><div style={{fontSize:13,fontWeight:700,color:"#e8f0f5"}}>Xu hướng khách hàng</div><div style={{fontSize:9,color:"#7890a2",marginTop:3}}>{period==="WEEK"?"Theo ngày":"Tổng hợp theo tuần"}</div></div><div style={{fontSize:9,color:"#7890a2"}}>Adult ≥ 18 · Child &lt; 18</div></div>
   <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7,marginBottom:8}}><Kpi label="LƯỢT KHÁCH-LƯU-TRÚ" value={money(customerTotals.adults+customerTotals.children)} note={`Toàn bộ ${period==="WEEK"?"7 ngày":"kỳ đã chọn"}`}/><Kpi label="ADULT" value={money(customerTotals.adults)}/><Kpi label="CHILD" value={money(customerTotals.children)}/><Kpi label={period==="WEEK"?"NGÀY GẦN NHẤT":"TUẦN HIỆN TẠI"} value={money(latestCustomerValue)} note={latestLabel}/></div>
   <div style={{height:112}}><ResponsiveContainer width="100%" height="100%"><LineChart data={customerData} margin={{top:4,right:10,left:-16,bottom:0}}><CartesianGrid stroke="rgba(148,163,184,.08)" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fill:"#7890a2",fontSize:9}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fill:"#7890a2",fontSize:9}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"#0b1d2b",border:"1px solid #21445d",borderRadius:7,color:"#fff",fontSize:11}}/><Legend wrapperStyle={{fontSize:10}} iconType="circle" iconSize={7}/><Line type="monotone" dataKey="adults" name="Adult" stroke="#22c7ff" strokeWidth={2.3} dot={{r:2}}/><Line type="monotone" dataKey="children" name="Child" stroke="#19bf73" strokeWidth={2.3} dot={{r:2}}/></LineChart></ResponsiveContainer></div>
   {customerTotals.unknown>0&&<div style={{fontSize:9,color:"#7890a2",textAlign:"right"}}>{money(customerTotals.unknown)} lượt thiếu BirthDate không phân loại Adult/Child.</div>}
  </section>}
  {revenue&&<section>
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginBottom:8}}><div><div style={{fontSize:13,fontWeight:700,color:"#e8f0f5"}}>Xu hướng doanh thu</div><div style={{fontSize:9,color:"#7890a2",marginTop:3}}>{period==="WEEK"?"Theo ngày":"Tổng hợp theo tuần"}</div></div><strong style={{fontSize:12,color:"#e8f0f5"}}>{money(revenueTotals.total)} đ</strong></div>
   <div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:9}}><div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7,marginBottom:6}}><Kpi label="DOANH THU KỲ" value={`${money(revenueTotals.total)} đ`} note={`Toàn bộ ${period==="WEEK"?"7 ngày":"kỳ đã chọn"}`}/><Kpi label={period==="WEEK"?"NGÀY GẦN NHẤT":"TUẦN HIỆN TẠI"} value={`${money(latestRevenueValue)} đ`} note={latestLabel}/></div><div style={{height:112}}><ResponsiveContainer width="100%" height="100%"><LineChart data={revenueData} margin={{top:4,right:8,left:-4,bottom:0}}><CartesianGrid stroke="rgba(148,163,184,.08)" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fill:"#7890a2",fontSize:9}} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>`${Math.round(Number(v)/1_000_000)}m`} tick={{fill:"#7890a2",fontSize:9}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>`${money(Number(v))} đ`} contentStyle={{background:"#0b1d2b",border:"1px solid #21445d",borderRadius:7,color:"#fff",fontSize:11}}/><Line type="monotone" dataKey="total" name="Tổng doanh thu" stroke="#22c7ff" strokeWidth={2.5} dot={{r:2}}/></LineChart></ResponsiveContainer></div></div>
   <div style={{borderLeft:"1px solid rgba(148,163,184,.12)",paddingLeft:9}}><div style={{fontSize:10,color:"#a3b4c0",marginBottom:3,fontWeight:600}}>Cơ cấu kỳ</div><div style={{height:82}}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={revenueMix} dataKey="value" nameKey="name" innerRadius={21} outerRadius={33} stroke="none">{revenueMix.map((x,i)=><Cell key={x.name} fill={UNIT_COLORS[i]}/>)}</Pie><Tooltip formatter={v=>`${money(Number(v))} đ`} contentStyle={{background:"#0b1d2b",border:"1px solid #21445d",borderRadius:7,color:"#fff",fontSize:10}}/></PieChart></ResponsiveContainer></div><div style={{display:"grid",gap:3}}>{revenueMix.map((x,i)=><div key={x.name} style={{display:"grid",gridTemplateColumns:"7px 42px 1fr",gap:4,fontSize:9,alignItems:"center"}}><span style={{width:6,height:6,borderRadius:"50%",background:UNIT_COLORS[i]}}/><span style={{color:"#a3b4c0"}}>{x.name}</span><strong style={{textAlign:"right",color:"#d6e0e7"}}>{revenueTotals.total?`${(x.value*100/revenueTotals.total).toFixed(1)}%`:"0%"}</strong></div>)}</div></div></div>
  </section>}
 </div>;
}